### ISSUE TITLE
package:crud_todo_app/firebase_options_dev.dart

### ISSUE THREAD

**Issue by Bakann** [FabianVarela/crud_todo_app#6]
In main.dart, this package doesn't exist : crud_todo_app/firebase_options_dev.dart'. 
Same for main_dev.dart with crud_todo_app/firebase_options_dev.dart

**Comment by Bakann** [comment]
Je suis en train lire ton code, qu'est-ce que c'est bien écrit!

**Comment by FabianVarela** [comment]
Hi @Bakann. I have edited the [Readme](README.md) file specifying how to run the `flutterfire` commands to generate the `firebase_option` files for the `dev` and `production` environments. Don't forget to create your Firebase projects and execute the commands.
